# -*- coding: utf-8 -*-
"""ai-resume-analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/sourav909090/70b89c3a0e7f6b95d27b3d932e016914/ai-resume-analyzer.ipynb
"""



from google.colab import files
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

!pip install PyPDF2

import PyPDF2
def read_resume(file_path):
   text = ""
   with open(file_path, "rb") as file:
       reader = PyPDF2.PdfReader(file)
       for page in reader.pages:
           text += page.extract_text()
   return text
print(read_resume(file_name))

pip install google-genai

from google.colab import userdata

from google import genai
client = genai.Client(api_key=userdata.get('GOOGLE_API_KEY'))

def analyze_resume(text):
   response = client.models.generate_content(
       model="gemini-3.6-flash",
       contents=f"Analyze this resume and give feedback:\n{text}"
   )
   return response.text



def analyze_resume(text):
   response = client.models.generate_content(
       model="gemini-3.6-flash",
       contents= f"""
You are an ATS resume analyzer.

Analyze the resume below and return ATS score and feedback.

Resume:
{text}

Return in JSON format with:
- ats_score (0-100)
- summary
- strengths
- weaknesses

Rules:
- Output ONLY JSON
- No extra text
"""
   )
   return response.text

resume_text = read_resume(file_name)
result = analyze_resume(resume_text)
print(result)
